### ISSUE TITLE
Unable to print using `std::wcout`, `std::wcerr` and `std::wclog`

### ISSUE THREAD

**Issue by JustWhit3** [JustWhit3/ptc-print#9]
**Describe the bug**
The `ptc::print` function is unable to print using `std::wcout`, `std::wcerr` and `std::wclog` wostream objects. An error occurs:

```
../include/ptc/print.hpp:431:11: error: no match for ‘operator<<’ (operand types are ‘std::basic_ostream<wchar_t>’ and ‘const std::__cxx11::basic_string<char>’)
  431 |        os << getEnd();
      |        ~~~^~~~~~~~~~~
```

**To Reproduce**
1. Compile this line of code: `ptc::print( std::wcout, "Something" )`

**Expected behavior**
I am expecting to have a clean compilation.

**Comment by MiiKaa3** [comment]
Just noting that the important part of the error is:
```
no match for ‘operator<<’ (‘std::basic_ostream<wchar_t>’ and ‘const std::__cxx11::basic_string<char>’)
  431 |        os << getEnd();
```
At this stage, we store end and sep as std::strings, which are char arrays under the hood. This data type is incompatible with wide chars, wchar_t.  This begs fundamental questions about the architecture of the package, and how we should store the data. 

imo the cleanest solution would be to template the the whole struct `ptc::print` with a datatype, `T`, then declare the private data according to that data type `T end, sep;`.  Finally, when you declare the class for the user end: `481 | inline Print print;` change it to `481 | inline Print print<std::string>;`. We can then choose to also include `482 | inline Print printw<std::wstring>;` or not, and leave it up to the user to decide. Writing this on the bus atm, but ill write a PR with this solution as soon as im home.

**Comment by JustWhit3** [comment]
Thank you very much @MiiKaa3. I think that the solution you proposed is the most suitable one to solve this issue. I think that we could also declare the `std::wstring` variation of `ptc::print` inside the same header, as we did for the standard `std::string` declaration.

Just a small suggestion, maybe it would be better to call the new print variation `ptc::wprint` instead of `ptc::printw` in order to be more consistent with `wstring.`

Waiting for your PR, meanwhile I'll focus on other implementations.

Thank you very much again!
